# Generated by Django 5.2.4 on 2025-08-05 21:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadedMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("thread_depth", models.PositiveIntegerField(default=0)),
                (
                    "parent_message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="chats.threadedmessage",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threaded_received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threaded_sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["sender", "timestamp"],
                        name="chats_threa_sender__24d309_idx",
                    ),
                    models.Index(
                        fields=["receiver", "timestamp"],
                        name="chats_threa_receive_76ceaa_idx",
                    ),
                    models.Index(
                        fields=["parent_message", "timestamp"],
                        name="chats_threa_parent__583367_idx",
                    ),
                    models.Index(
                        fields=["thread_depth"], name="chats_threa_thread__b6163b_idx"
                    ),
                ],
            },
        ),
    ]
